### ISSUE TITLE
document the relationship of swiftz, swiftz_core, and basis

### ISSUE THREAD

**Issue by maxcan** [typelift/Swiftz#109]
So, there was a bigish pull request #105 for rejigging things to merge into https://github.com/typelift/Basis.  That was closed without merging.  Would it be possible for someone to explain, probably best on the readme, the relationship between the projects and modules?

**Comment by liweiz** [comment]
A bit offtopic. Just had a look at Basis. Is that a repo for layman like me to learn fp in Swift and using Swiftz? I'm trying to learn fp with Swiftz, but the learning curve for beginners seems high. What I'm doing is to try to read through the code in Swiftz to learn(and yes, a lot of Google), but I'm also looking for better ways. I read through the readme file over there, but still hope to get a clearer answer.

I know it has nothing to do with this repo to provide materials for learners. However, this perhaps the best place to ask this question.

Thanks in advance,

Liwei

**Comment by CodaFi** [comment]
@liweiz Good thing you brought this up, actually.  I've changed the raison d'être for the Basis to be exactly that.  It is a library for exploration and learning rather than expressing idioms (which is what Swiftz is for).  Open your comment as an issue over there.

**Comment by liweiz** [comment]
@CodaFi Thanks a lot for your quick reply. I'll open my comment as an issue there:)

**Comment by CodaFi** [comment]
In light of recent restructuring, this issue has become irrelevant.
