### ISSUE TITLE
Housekeeping

### ISSUE THREAD

**Issue by CodaFi** [typelift/swiftz#118]
A few notes on housekeeping for the framework:

<strike>Whitespace</strike>
---------------

<strike>Right now we're using both tabs, two, and four spaces per indent.  I'd prefer tabs if it's all the same.
(#flamewar)</strike>

<strike>Project Structure</strike>
----------------------

<strike>It is confusing as all hell to get this framework set up properly because we don't have two different projects for the iOS and OS X versions of this framework.  To remedy the situation, I'd just revise the project to use the structure I've got in the other frameworks under typelift:</strike>

<strike>- An OS X project</strike>
<strike>- An iOS project</strike>
<strike>- A unified workspace</strike>

<strike>All target names resolve to just `swiftz` and `swiftz_core` instead of `swiftz_ios`, and `swiftz_core_ios` this way.  And it keeps Xcode sane.  Currently, when you try to add the framework to "copy files" it pulls both and makes the linker vomit if you pick the wrong one (i.e. the one that shows `in build/Debug[-iphoneos]` in tiny gray text).  There should only be two visible options when you use this thing, and this is the only way to enforce it.  The only downside is new files have to be put into both xcode projects, but that's what the big workspace is for anyways.
</strike>

Readme
-----------

Looks like it hasn't been updated in a while.  Perhaps a rewrite is in order.  The installation instructions are bare and rather draconian.

**Comment by bontoJR** [comment]
It would be great to add version 'tags' in the master branch to support Carthage builds.

**Comment by CodaFi** [comment]
I'll tag 0.1.0 once #164 is merged and any post-cleanup has happened.  By then, this issue will also go away because all open pull requests solve it.

**Comment by CodaFi** [comment]
Resolved completely by #149
