### ISSUE TITLE
Subtree Split the Core

### ISSUE THREAD

**Issue by CodaFi** [typelift/swiftz#142]
Related to #118 

I think with #131 it's high time the core became its own µFramework and possibly get a name change.

Thoughts, ideas, names, cash, I'll take them all.

**Comment by CodaFi** [comment]
Reminds me too much of my poor Swift-Extras :)

Spitballing Here:

- LambdaKit
- CoreFP
- SwiftPlus
- Abstraction
- TypeKit
- Prelude
- STLExt
- LiftKit

**Comment by pthariensflame** [comment]
How about TLKit, if we want that style of name?

**Comment by CodaFi** [comment]
Or 

- LiftedSwift
- BaseLift
- TypeLiftCore
- CoreData /s

**Comment by gfontenot** [comment]
... CoreData seems like a bad choice.

**Comment by CodaFi** [comment]
@gfontenot :smiling_imp: 

@pthariensflame 
This is tough... I'd prefer we follow both the Swift and Cocoa framework naming conventions.  Cocoa necessitates expanding acronyms and either ending with -Kit, or beginning with Core.  Swift prefers concrete nouns.  That means either `TypeLiftKit` (which implies we're sticking *all* the work of the org in one place), or some other noun that truly encapsulates what it means to cram a bunch of foundational data types into a lib -without calling it Foundation :P.

**Comment by CodaFi** [comment]
OK.  Let's a least offer 3 of our favorites so we can narrow the field.  No decisions yet:

For me it's

- AirLift
- TLKit
- LiftKit

**Comment by pthariensflame** [comment]
Of those, three, I favor `TLKit`, but not super-strongly.

**Comment by CodaFi** [comment]
@pthariensflame Do you have two more suggestions picked out?

**Comment by pthariensflame** [comment]
I think I already suggested SwiftX, but I could also maybe get behind SwiftFP, or TLCore, or most anything of those patterns.

**Comment by CodaFi** [comment]
CoreFP maybe (punning CoreFoundation)... I'm starting to warm to that kind of name.

**Comment by CodaFi** [comment]
:bulb: How about a different stylization of SwiftX?  As in Swiftx.  If you want full Swiftz, you just move over a key :)

**Comment by pthariensflame** [comment]
Swiftx is perfect!

**Comment by CodaFi** [comment]
Then.

Tonight's the night.

**Comment by CodaFi** [comment]
Finished.
