### ISSUE TITLE
Monad Operations as a typeclass?

### ISSUE THREAD

**Issue by CodaFi** [typelift/Swiftz#143]
I've been playing around with generalizing the Monad operators so we don't have to write them all out for a couple months and have come to the conclusion it's just too inelegant even if it were possible.  In the spirit of choosing the lesser of two evils, and not furthering bloat in `Monad`, I think the best course of action is to factor out the operators and functions into some kind of `MonadOps` protocol and implement them all.  

It's a one-time yak shaving, but a yak shaving all the same.

Related to #136

**Comment by pthariensflame** [comment]
In response to discussion on typelift/Aquifer#10, we should consider using `>>->>` for (forward) Kleisli composition.

**Comment by CodaFi** [comment]
Fixed by the merge of #249.
