### ISSUE TITLE
Fix duplication of `Box`

### ISSUE THREAD

**Issue by pthariensflame** [typelift/swiftz#157]
While working on [Aquifer](https://github.com/pthariensflame/Aquifer), I came across the issue that the Swift compiler couldn't tell what I meant by `Box`.  It turns out there is a `Box` type in Swiftz and a *seperate* (but identical) `Box` type in Swiftz_core!  This needs to be fixed.

**Comment by CodaFi** [comment]
I see one Box def in this entire repository, and while it may live in the Core directory I thought I removed the core as a dependency and just included the files anyway so you wouldn't have to link both libraries.

**Comment by pthariensflame** [comment]
Ah, that was the problem, then!  I was linking both.  Perhaps we should put a warning of some sort in the Readme?

**Comment by CodaFi** [comment]
Bump #149

**Comment by CodaFi** [comment]
Fixed by #149
