### ISSUE TITLE
Should fmap use <§> for consistency with function application: §?

### ISSUE THREAD

**Issue by ryanbooker** [typelift/Swiftz#159]
In Haskell, I think `<$>` was chosen for fmap, because `$` is used for function application. Perhaps this consistency should be brought to Swiftz's fmap.

Should fmap use `<§>` for consistency with function application: `§`?

**Comment by sharplet** [comment]
I wish `<§>` wasn't such hell to type :disappointed:

**Comment by CodaFi** [comment]
I use <%> in the basis because it was the closest thing to <$> on the keyboard.  I wonder what other languages with Applicative Functors do.

**Comment by pthariensflame** [comment]
I think I like `<§>` rather than `<$>`, for the reasons cited in the OP.  That being said, I'll go with whatever is most comfortable with the general populace of our users, since Swiftz is above all else supposed to be *usable*.  :)

**Comment by ryanbooker** [comment]
re: the "hard to type" fear, `§` is just as easy to type as `$`, `^` or `%`… it's `⌥ 6` on a Mac keyboard. Just an idea.

**Comment by pthariensflame** [comment]
Option-5, for me, since I'm using U.S. Extended.  :)

**Comment by ryanbooker** [comment]
Ah, fair enough. I suppose it may be cumbersome for some language keyboards?

**Comment by sharplet** [comment]
@pthariensflame Actually what I was getting at was that you have to switch modifier keys and back again: `Shift-,` - `Opt-6` - `Shift-.`. I personally find it quite cumbersome, but maybe I'm doing it wrong? Compared to `<*>`, `<%>`, or `<^>`, where you can just hold down shift and you're off to the races.

**Comment by sharplet** [comment]
But I'm also a big fan of the consistency argument, so really I'm just torn!

**Comment by pthariensflame** [comment]
@sharplet You can have your thumb (of either hand) on Option while your pinky finger (also of either hand) is on Shift.  This is generally what I do, and it works pretty well (it's also agnostic to your particular keyboard layout, since the MOD keys aren't going to move

**Comment by CodaFi** [comment]
As an aside: we really should radar for the use of $ in identifiers.  It's ridiculous that the language designers get to have it all to themselves just because they use it once somewhere.

**Comment by pthariensflame** [comment]
Thanks, @CodaFi!

**Comment by CodaFi** [comment]
This thread should be moved into typelift/Operadics.  I'm going to close it here.  If there's any interest reopen it over there.
