### ISSUE TITLE
Rename the Targets

### ISSUE THREAD

**Issue by CodaFi** [typelift/swiftz#161]
Currently, Xcode shows we haven targets named swiftz, swiftz_ios, swiftz_core, swiftz_core_ios and Swiftz.  In the interest of reducing the entropy of the system, and to facilitate future refactoring, I propose a split like the Basis so we export sane target names for the two disparate architectures:

(Names are nonfinal):

```
Swiftz.xcworkspace exports
    Swift.xcodeproj exports
        - Swiftz (capitalized)
    Swiftz-iOS.xcodeproj exports
        - Swiftz (capitalized)

SwiftX.xcworkspace exports
    SwiftX.xcodeproj exports
        - SwiftX (capitalized)
    SwiftX-iOS.xcodeproj exports
        - SwiftX (capitalized)
```

**Comment by pthariensflame** [comment]
Looks good to me!  This might let Carthage actually build it directly, as well.

**Comment by CodaFi** [comment]
I was worried about how this interacts with Carthage.  When it builds frameworks in workspaces, do the individual projects get their own directory?  Worst case scenario: xcodebuild dumps both frameworks into the same directory and bad things happen™

**Comment by CodaFi** [comment]
Also, I'd like to interleave this with the solution to #142. Ideally we

- Rename Swiftz_Core
- Perform a Subtree Split
- Fix the workspace.

**Comment by pthariensflame** [comment]
Carthage in particular shouldn't have a problem, as it only ever builds one target (if it can find one, which is apparently harder than it looks, given the troubles we've had).  In general, though, ...

Yeah, we should take a look at what actually happens, just in case.  :/

**Comment by pthariensflame** [comment]
Also integrating with #142 is such a good idea I had though that was the plan from the beginning.  :)

**Comment by CodaFi** [comment]
I say that because the Basis appears to only be building the Mac target for some reason.  I'll investigate a bit after the subtree split.

**Comment by CodaFi** [comment]
Closing; #164
