### ISSUE TITLE
Implement The Coproduct of Monoids

### ISSUE THREAD

**Issue by CodaFi** [typelift/swiftz#172]
```swift
struct MonoidCoproduct<A : Monoid, B : Monoid> : Monoid {
    let stuff : [Either<A, B>]
}
```

(Also, think of a better name for this thing).

**Comment by pthariensflame** [comment]
This should actually be `[(A, B)]` on the inside, because of monoidal collapse.

**Comment by CodaFi** [comment]
Strictly alternating pre-products get tricky with strict languages.
