### ISSUE TITLE
Carthage Is Only Building The Mac Scheme

### ISSUE THREAD

**Issue by CodaFi** [typelift/Swiftz#173]
Running `carthage build --no-skip-current` causes only the OS X project to be found and that scheme to be built by Carthage.  In some rare cases (after first checkouts for libraries that depend on Swiftx and Swiftz), Carthage will report that it cannot find the Swiftz-iOS scheme, but future attempts to run `carthage build` will not report said error further.

I'm not entirely sure how to fix this one.  `xcodebuild` can see all the right schemes in our project directory but nothing for iOS is being built.

//cc @jspahrsummers

**Comment by jspahrsummers** [comment]
Carthage reads schemes from _one_ project file. You'll have to put both platforms' targets in the same project for it to work.

**Comment by CodaFi** [comment]
Any way to make it find the workspace instead of the projects?

**Comment by jspahrsummers** [comment]
Nope.

**Comment by CodaFi** [comment]
Welp, I'll look into making that happen then.

For now, I know you're horrendously overbooked on the message front.  Thanks a ton!  :sparkles:

**Comment by ryanbooker** [comment]
Just wondering if there is any plan to have full Carthage support? Or even is there anything a contributor could do to help achieve that?

**Comment by CodaFi** [comment]
Until Carthage supports building workspaces or multi-project repos there's nothing I can see that can be done about this.  The only thing we can do is offer to keep `carthage build --no-skip-current` working for each target (which is becoming a PITA without Travis).

**Comment by jspahrsummers** [comment]
@CodaFi You can combine the targets into one project file. That's the typical thing to do anyways, because it helps with dependency resolution in _other_ multi-platform projects.

**Comment by CodaFi** [comment]
The frameworks have the same product name, which created some interesting errors when I last tried this.  Then again, that was months ago.  Let's see what happens.

**Comment by CodaFi** [comment]
@jspahrsummers Hmph, this is going swimmingly.  I can't recall a precise reason I starting splitting the project files, but whatever it was is gone now.

Looking forward to closing this.

**Comment by CodaFi** [comment]
Yay, everything works again!

Fixed by the merge of #197.

**Comment by jspahrsummers** [comment]
:sparkles:

**Comment by ryanbooker** [comment]
Fantastic. Thanks for that. Much appreciated. I'm glad I asked!

Is it intended that the iOS projects in Swiftx/z/Check have an 8.4 deployment target? This restricts the projects to Xcode 6.4 beta at the moment (i.e. builds fail with Xcode 6.3)… however the projects do build in Xcode 6.3 for 8.3 if you change the deployment target back manually.

**Comment by CodaFi** [comment]
That was put there by Xcode 6.4.  I haven't update the podspec because of it (It's release is imminent anyways).  If you'd like to submit a pull request changing it I'd merge it,

**Comment by pthariensflame** [comment]
@CodaFi You know, you can just have Xcode 6.4 download the "iOS 8.3 emulator" and it'll let you target 8.3 from then on.
