### ISSUE TITLE
Linkage error on latest master commit (after e3496d5, "Or not")

### ISSUE THREAD

**Issue by majorgilles** [typelift/swiftz#175]
Hello, I unfortunately cannot build the project on the latest commit (8a153c6).

I checked out on e3496d5 and was able to build the project, following the same steps as described in the tutorial (Carthage method). This wasn't possible with latest commit.

**Comment by CodaFi** [comment]
Mmm, yeah.  I know exactly what's happened.  Gimme a few minutes.

**Comment by CodaFi** [comment]
OK.  Checkout #176 and make sure that's fixed everything for you.

**Comment by majorgilles** [comment]
worked fine on my end, thanks! (pr/176)

**Comment by CodaFi** [comment]
When Travis gives me the green light I'll merge it.

Thanks!
