### ISSUE TITLE
Multiparameter protocols

### ISSUE THREAD

**Issue by ejenk** [typelift/swiftz#18]
I want to define the notion of an action of one type on another. For instance, the CoreGraphics type CGVector represents a 2D vector, and CGPoint represents a point on the coordinate plane. There should be a function
`@infix |> (v: CGVector, p: CGPoint) -> CGPoint`
that translates the point p by the vector v. I'd like to implement this as a protocol:
```
protocol Action {
    typealias A
    typealias M
    @infix |> (a: A, x: M) -> M
}
```
and instantiate it by extension to the pair `(CGVector, CGPoint)`, but I get the error
`Non-nominal type '(CGVector, CGPoint)' cannot be extended.`
I can't think of a good workaround for this.

In Idris, I could implement this with a multiparameter typeclass:
```
class Action a m where
 (|>) : a -> m -> m
```
and then instantiate it as
```
instance Action CGVector CGPoint where
  (mkCGVector a b) |> (mkCGPoint c d) = mkCGPoint (a + c) (b + d)
```
where `mkCGVector` and `mkCGPoint` are the sole constructors of `CGVector` and `CGPoint`, respectively

**Comment by CodaFi** [comment]
@ejenk Given we're now at 1.1, I don't have high hopes for us getting multi-parameter typeclasses, and even less for the chance you'll get any kind of verification of rules.  There's serious language limitations standing between you and satisfaction that Swift will probably never be able to satisfy.  You can certainly fake it, and fake it hard, with individual witnesses like Max was saying, but it quickly turns into a Yak shaving competition.

For now I will close this issue, but rest assured any breakthroughs or midnight epiphanies means this gets reopened.
