### ISSUE TITLE
Swift 1.2 Support

### ISSUE THREAD

**Issue by BrianDoig** [typelift/Swiftz#182]
Swiftz currently does not compile under Swift 1.2 due to changes in how auto closures are handled and HeapBuffer no longer being available and replaced with ManagedBuffer that has different semantics.

At some point Swiftz will need to be converted to be compatible with Swift 1.2 (currently found is Xcode 6.3 beta).

**Comment by CodaFi** [comment]
Way ahead of you, bro #181

**Comment by BrianDoig** [comment]
Sweet!  Didn’t see that when I looked at the branches.

On Feb 10, 2015, at 4:01 PM, Robert Widmann <notifications@github.com<mailto:notifications@github.com>> wrote:


Way ahead of you, bro #181<https://github.com/typelift/Swiftz/pull/181>

**Comment by CodaFi** [comment]
OK.  6.3 is public today, so we're just waiting on travis-ci/travis-ci#3216

**Comment by rodrigoelp** [comment]
Do we know how much is it going to be until the merge happens?

**Comment by CodaFi** [comment]
I won't go through with a merge until Travis can give us the thumbs up (see the issue).

**Comment by CodaFi** [comment]
Okay, this is starting to get ridiculous.

I'm throwing in the towel for now on Travis (a month is too long to hold up features and releases).  #181 will be merged automatically this Friday regardless of our build status at that time.

**Comment by CodaFi** [comment]
Done!

Fixed by the merge of #181
