### ISSUE TITLE
Is there a way to extract a sub-JSONValue from a JSONValue ?

### ISSUE THREAD

**Issue by raphaelmor** [typelift/Swiftz#188]
Is there a way to extract subparts of a `JSONValue` and feed it to `fromJSON`

e.g. (based on README sample)
```swift
let userjs = "{\"user\": {\"name\": \"max\", \"age\": 10, \"tweets\": [\"hello\"], \"attrs\": {\"one\": \"1\"}}}"

let json = JSONValue.decode(userjs)
let user = (json <? "user") >>- User.fromJSON

```

`JSONValue` can't implement `JSONDecodable` because `JSONDecodable` needs a `class func`.
And I don't seem to find a simple way to do that.

The naive switch/case seems a bit cumbersome :
```swift
var user : User?
     
if let value = JSONValue.decode(userjs) {
    switch value {
    case let .JSONObject(dict):
        user = dict["user"] >>- User.fromJSON
    default:
        user = nil
    }
}
```

**Comment by CodaFi** [comment]
You're asking for something that I can't express in Swift.  Lenses into JSON + this stuff requires higher kinded types at a minimum (for Traversals).  We can implement a stopgap, but it seems to me NSJSONSerialization is good for getting the subpart.

**Comment by CodaFi** [comment]
It's been 3 months, so I will go ahead and close this

A lot has changed between now and then, so if you have any updates feel free to open a new issue or reopen this one as appropriate.
