### ISSUE TITLE
Remove Tuple2?

### ISSUE THREAD

**Issue by CodaFi** [typelift/Swiftz#196]
I'm not entirely sure why it's in here in the first place.

**Comment by CodaFi** [comment]
Deprecated in #255.  Will be removed very soon.

**Comment by mpurland** [comment]
```Tuple2``` is still here even though Swift 2 support went in. Shall I do a PR to remove it?

**Comment by CodaFi** [comment]
Yes please!

**Comment by CodaFi** [comment]
Whoa, we fixed this [a long time ago](https://github.com/typelift/Swiftz/pull/290).
