### ISSUE TITLE
Why Are We Right Biased In Either?

### ISSUE THREAD

**Issue by CodaFi** [typelift/Swiftz#200]
See: https://github.com/non/cats/issues/189

**Comment by pthariensflame** [comment]
Because we're following Haskell.  If we were to follow Rust instead, we'd end up renaming it to `Result` (with constructors `Ok` and `Err`) and making it left biased.  :)

**Comment by CodaFi** [comment]
They have another structure called XOr that is left biased that might be nice to ha
