### ISSUE TITLE
Current podspec has wrong version specified / Swiftx not retrieved

### ISSUE THREAD

**Issue by jdesiloniz** [typelift/Swiftz#202]
Hi!

We're trying to use CocoaPods to use your library in a project and we just noticed that the version specified is referencing tag v0.2.1 instead of v0.2.2. We also are having problems getting the library as it seems that Swiftx-dependant types like Box are not being retrieved by the pod install command, and of course that leads to the project not being able to compile.

Does the latter maybe have something to do with the former? Any clue?

Thanks! :)

**Comment by pthariensflame** [comment]
No idea what might be wrong, but I'll update the version in the podspec.

**Comment by jdesiloniz** [comment]
Thanks a lot for updating the version @pthariensflame !!

Swiftx is already working for us... we weren't using submodules in our Podfile. Sorry about that! :)

**Comment by pthariensflame** [comment]
No problem!  So is this issue now resolved, then?

**Comment by jdesiloniz** [comment]
Yes! Thanks!

**Comment by pthariensflame** [comment]
Great.
