### ISSUE TITLE
Podspec not published

### ISSUE THREAD

**Issue by jdesiloniz** [typelift/Swiftz#203]
Hi

We're creating a framework that depends on Swiftz, and we're starting to get ready our podspec file for people to install it with CocoaPods. The thing is that when we try to set the dependency on Swiftz in our podspec, it seems that your podspec hasn't been submitted to the git containing all the podspecs and it can't find it.

We thought that we could set the dependency pointing directly to your repository but it seems that it isn't supported: https://github.com/CocoaPods/CocoaPods/issues/885

Would it be possible for you to submit your podspec?

Thanks a lot!

**Comment by CodaFi** [comment]
But... That's impossible.  I pushed that pod to trunk myself at least once... 

@pthariensflame perhaps this is related to the last fix?

**Comment by CodaFi** [comment]
OK, I've pushed the podspec to trunk.  Give it a bit and try again.

**Comment by CodaFi** [comment]
@jdesiloniz The podspec is up so I'm going to close this.  Reopen it if you encounter further issues.

Cheers! :sparkles:
