### ISSUE TITLE
Minimum required target

### ISSUE THREAD

**Issue by jdesiloniz** [typelift/Swiftz#206]
Hi!

For some reason the current minimum deployment target for Swiftz is 8.4, which isn't even officially released. Is there a reason for this? We've noticed that using 8.1 works OK with the library and 8.0 should be also OK. We're using Swiftz in a library and while it works OK, it displays a couple of warning messages as our library supports 8.0 and Swiftz a higher minimum target.

Would it be possible to change this?

Thanks a lot for your quick responses!! (you'll be getting tired of my issues :P).

**Comment by CodaFi** [comment]
It has been changed in the latest dot releases and not pushed to cocoapods yet (I'm trying to put out a larger release with more bug fixes).  If this is a show stopper I can forgo my plans and push anyway.

**Comment by CodaFi** [comment]
Looks like my evil plans worked out before you could respond again.

Should be all patched up now.
