### ISSUE TITLE
Pointed instances for Pointer Types

### ISSUE THREAD

**Issue by CodaFi** [typelift/Swiftz#213]

**Comment by CodaFi** [comment]
This is a very dangerous proposition, now that I think about it.  In Scala and Haskell you have the GC around to clean up most Ptr mistakes.

**Comment by pthariensflame** [comment]
Yeah, this isn't Rust.  We don't have any way to tell the compiler that our references should only be valid for the duration of the original object.  :(

**Comment by CodaFi** [comment]
Closing.
