### ISSUE TITLE
Split Optics Into A New Framework?

### ISSUE THREAD

**Issue by CodaFi** [typelift/Swiftz#214]
I think it would be worth it to make optics (and their underlying Indexed monads and comonads) their own micro-framework.  They already rely so little upon primitives in Swiftz and Swiftx, and we're not treating them like first-class citizens enough, to the point it doesn't make sense to keep them part of the larger repo.

**Comment by vendethiel** [comment]
I tried to (github) (file) search for "optics" and "optic" and didn't find anything. I don't know much, so which files are you talking about?

**Comment by CodaFi** [comment]
Our little lens hierarchy and anything with an Ix in it.

**Comment by pthariensflame** [comment]
I'd be OK with maintaining them separately, if we do decide to split them out.

**Comment by CodaFi** [comment]
@pthariensflame I think now is the time to do it, especially with the Swift 2.0 changes going into a new release.  Got a name?  Lens, Optics?

**Comment by pthariensflame** [comment]
Well, `lens` is already taken in Haskell, and I'm using `refraction` and `TeaLeaves` for my WIP ports to Rust and Ceylon, respectively.  My attempt at one for Scala (before `Monocle` existed) was called `Lentil`…

How about `Bifocals`?

**Comment by CodaFi** [comment]
Focal.framework has a nice ring to it.

**Comment by pthariensflame** [comment]
Or, rather than the awkward adjective, how about `Focus`?

**Comment by CodaFi** [comment]
RefractiveCocoa :trollface:

**Comment by CodaFi** [comment]
:warning: Executive decision made :warning:

#216 will be assimilated into [Focus.framework](https://github.com/typelift/Focus)
