### ISSUE TITLE
Nested maps and static map functions

### ISSUE THREAD

**Issue by badeleux** [typelift/Swiftz#228]
Hello,

I was trying to implemented nested mapping in swiftz. Let's say function we have a function `A` which returns `Optional<[String]>`. I would like to map result of `A` to `Optional<[Phrase]>`. 

`{ar in Phrase.create <^> ar} <^> A`

It works and it compiles but it doesn't look good. For me it lacks static `Array.map` function which will turn above expression into this:

```
extension Array {
    static func map<A,B>(f:A -> B)(_ inArray: [A]) -> [B] {
        f <^> inArray
    }
}

`Array.map(Phrase.create) <^> A`
```

Which complains `Cannot invoke 'map' with an argument list of type ((String) -> Phrase)`

1. Any idea why it complains?
2. Do you plan to add static functions like this? Or maybe they are completely redundant because there is better way to solve this problem?

**Comment by CodaFi** [comment]
I'll kill two birds with one stone here: yes, it is redundant.  Every non-static member function of a Swift class or structure actually takes the form `Self -> Args ... -> Result`.  Combine this with the fact that we implement `fmap` [as just `map`] and you get a function that behaves exactly as you intended (albeit with flipped arguments, but we [have combinators for that](https://github.com/typelift/Swiftx/blob/swift-development/Swiftx/Combinators.swift#L30-L34)):

    Array.fmap(Phrase.init) <^> arbitraryFunctionA

As for your elegance problem, one of the Functor laws states that we can rewrite 

    x.fmap(g).fmap(f)

as

    (f • g) <^> xs

**Comment by badeleux** [comment]
Solution is awesome. I have one doubt:

` Every **non-static** member function of a Swift class or structure actually takes the form Self -> Args ... -> Result, you just get to see the form where self is partially applied in normal use cases. Your typechecker woes are a **direct consequence of this**`

My static map implementation is a static function, isn't it?

**Comment by CodaFi** [comment]
So it is.  Assuming your types are all correct, I'd be willing to bet it can't see your overload of map.  This would make for an interesting bug report.
