### ISSUE TITLE
[Announcement] TypeLift is Moving to Protected Branches

### ISSUE THREAD

**Issue by CodaFi** [typelift/Swiftz#248]
With the introduction of GitHub's new [protected branches](https://github.com/blog/2051-protected-branches-and-required-status-checks) feature, we have a new way to close off the many avenues I know of screwing up the repo.  Therefore, effective immediately, TypeLift will move to an aggressive protection policy for master and less-aggressive protection policies for satellite branches.

**Comment by vendethiel** [comment]
Seems like a great github change :+1:

**Comment by pthariensflame** [comment]
Yay!

**Comment by CodaFi** [comment]
It is done
