### ISSUE TITLE
Injection / Bijection wanted?

### ISSUE THREAD

**Issue by sritchie** [typelift/Swiftz#25]
Hey guys,

I'm the author of Twitter's [Bijection](https://github.com/twitter/bijection) library in Scala, and have found the Injection and Bijection typeclasses to be extremely useful. I'd love to get these, and a few other typeclasses, into swiftz. Here's some extremely early playing around:

```swift
// Playing around with the Injection typeclass.
protocol Injection {
    typealias T
    typealias U
    func apply(T) -> U
    func invert(U) -> T?
}

class IntInjection: Injection {
    func apply(i: Int) -> String {
        return String(i)
    }
    func invert(s: String) -> Int? {
        return s.toInt()
    }
}

let i = IntInjection()
i.apply(10)
i.invert("10")
```

Would you guys be interested in taking this pull req? I don't want to send it over if this is beyond the library scope.

One other Q:
- Would you take pull reqs for implementations of associative datastructures like those in [Algebird](https://github.com/twitter/algebird)? Or is Swiftz meant to contain typeclasses only?

**Comment by CodaFi** [comment]
Advancement of the Data.Lens stuff makes this issue a bit irrelevant at the moment.  Closing.
