### ISSUE TITLE
Support for swift-2.0

### ISSUE THREAD

**Issue by zbeckman** [typelift/Swiftz#252]
Will there be a Swift 2.0 / Xcode 7 compatible release in the near future? (Current `swift-develop` branch has a lot of errors).

**Comment by CodaFi** [comment]
Yes.  I'm planning to release with/slightly before Xcode 7 on all of TypeLift.

**Comment by zbeckman** [comment]
Thanks. (Assuming you know that Xcode 7 GM is out – so, effectively it has been released, there will be no changes between the gold master and the final version).

**Comment by CodaFi** [comment]
It's not about the lack of changes so much as my lack of faith there won't be some breaking something or other with Swift between GM and release.  That and I need time to prepare the entire organization for this switch which takes some non-zero amount of time.

**Comment by zbeckman** [comment]
Happy to help test it out... ;-) I'm on the crux of a project and have to choose either SwiftyJSON, Scalaz, or some other solution. Hoping a Swift 2 branch shows up soon – I'd much prefer to use Scalaz.

**Comment by CodaFi** [comment]
Basically the sooner SwiftCheck gets updated the sooner everything else does too.

**Comment by CodaFi** [comment]
Fixed by the merge of #255
