### ISSUE TITLE
dyld: Library not loaded: @rpath/Swiftz.framework/Swiftz

### ISSUE THREAD

**Issue by zbeckman** [typelift/Swiftz#253]
After pulling the latest Carthage from `swift-develop` and:

1. Adding to the Link Binaries phase,
2. Adding to the Copy Files phase,

I'm getting the following linker error while trying to run any of our test targets in our app:
```
dyld: Library not loaded: @rpath/Swiftz.framework/Swiftz
  Referenced from: /Users/zbeckman/Library/Developer/CoreSimulator/Devices/FCFAAFBF-1AB4-4223-9BCC-CA91CBDE96DC/data/Containers/Bundle/Application/890D53F8-BB1B-4F38-A5ED-C538A7D1BC9B/Glimpulse.app/Glimpulse
  Reason: image not found
(lldb) 
```

**Comment by zbeckman** [comment]
And trying with the Podfile results in a lot of operator-specific errors.

**Comment by CodaFi** [comment]
Is the destination for the copy files phase /Frameworks?

**Comment by zbeckman** [comment]
Yes – but... I reset to a clean build, did it all over again, and this time it worked. :( Maybe stale info in derived data. Sorry for the distraction – and glad it is working!

*However, the issue with the Pod version is still there... but I think you are well aware of that one.*

**Comment by CodaFi** [comment]
I've just pushed 0.3.0 now. If that does it then close this.

**Comment by CodaFi** [comment]
I've just pushed the 0.3.0 pod.  Closing this.
