### ISSUE TITLE
Compiler error when installed this library via CocoaPods 0.39.0.beta.4

### ISSUE THREAD

**Issue by Hxucaa** [typelift/Swiftz#256]
The following error shows up during compilation.

<unknown>:0: error: filename "Operators.swift" used twice: '/Users/Lance/Desktop/Beluga/Example/Pods/Swiftz/Carthage/Checkouts/Swiftx/Carthage/Checkouts/SwiftCheck/Carthage/Checkouts/Operadics/Operators.swift' and '/Users/Lance/Desktop/Beluga/Example/Pods/Swiftz/Carthage/Checkouts/SwiftCheck/Carthage/Checkouts/Operadics/Operators.swift'
<unknown>:0: note: filenames are used to distinguish private declarations with the same name
<unknown>:0: error: filename "Operators.swift" used twice: '/Users/Lance/Desktop/Beluga/Example/Pods/Swiftz/Carthage/Checkouts/Swiftx/Carthage/Checkouts/SwiftCheck/Carthage/Checkouts/Operadics/Operators.swift' and '/Users/Lance/Desktop/Beluga/Example/Pods/Swiftz/Carthage/Checkouts/Swiftx/Carthage/Checkouts/Operadics/Operators.swift'
<unknown>:0: note: filenames are used to distinguish private declarations with the same name
<unknown>:0: error: filename "Operators.swift" used twice: '/Users/Lance/Desktop/Beluga/Example/Pods/Swiftz/Carthage/Checkouts/Swiftx/Carthage/Checkouts/SwiftCheck/Carthage/Checkouts/Operadics/Operators.swift' and '/Users/Lance/Desktop/Beluga/Example/Pods/Swiftz/Carthage/Checkouts/Operadics/Operators.swift'
<unknown>:0: note: filenames are used to distinguish private declarations with the same name
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

It seems there are duplicate `Operators.swift` files which cause the issue.

**Comment by CodaFi** [comment]
Is this really how CocoaPods works with dependencies like this?  We need those multiple definitions (compiled into different targets, obviously) to work around Swift's sad overloading resolution.  So, if you can come up with a way to alter our source search paths or something to fix this, I'm all ears.

**Comment by timbodeit** [comment]
Same for `0.39.0.beta.3`. Is there a known CocoaPods version for which it does work?

**Comment by CodaFi** [comment]
Fixed by the merge of #258.  Please update your dependency lists to tag `0.3.1`
