### ISSUE TITLE
Monoidal instead of Applicative

### ISSUE THREAD

**Issue by adamkuipers** [typelift/Swiftz#260]
The http://github.com/non/cats project has been exploring favoring the just as powerful (Monoidal)[https://wiki.haskell.org/Typeclassopedia#Alternative_formulation] typeclass over Applicative.

Applicative can be cumbersome in languages that don't default to partial function application and I also think it has a more intuitive definition than Applicative since it's symmetrical as well as having much nicer laws (naturality, left and right identity, and associativity).

You can also get apply builders almost for free since map2, map3, map4 just become map on tuple2, tuple3, tuple4.

**Comment by CodaFi** [comment]
This is awesome and I would love to see it happen, but alongside our current Applicative.  Swift does not support tuple extensions, so any generality we could extract would have to be by writing [7 billion overloads again](https://github.com/typelift/Swiftz/blob/master/Swiftz/Curry.swift).

**Comment by adamkuipers** [comment]
Yeah, there would probably have to be a `ProductN` boilerplate type like `Zip2Sequence`.

What I like about the `ProductN` route, though, is that it would only have to be used internally and would be transparent to the client. No longer will the client be required to define a curried initializer `create`.

Instead of `Foo.create <^> fa <*> fb <*> fc` we would have `map(fa, fb, fc) { Foo($0, $1, $2) }`, which looks more natural in Swift land IMO.

**Comment by CodaFi** [comment]
So, how much boilerplate is enough boilerplate then?

**Comment by CodaFi** [comment]
Which is to say, I definitely agree that that looks more natural, but am I gonna have to maintain 15 more structs in the near future?

**Comment by adamkuipers** [comment]
Scala seemed to have made the decision for everyone that `Tuple22` was enough 😃

**Comment by CodaFi** [comment]
Then to 22 we shall go!  Would you like to draw up a pull request, or shall I?

**Comment by adamkuipers** [comment]
I might have time tonight to get something going. Would you want Applicative to be defined in terms of Monoidal, vice versa, or independent of one another?

**Comment by CodaFi** [comment]
Do whatever is most natural (which probably means separate at first).  We'll worry about the nitty-gritty in code review.

**Comment by DanielAsher** [comment]
I've got Tuple to Tuple5 if that helps. Couldn't give up on shrinking in SwiftCheck...

**Comment by adamkuipers** [comment]
Unrelated, but have you considered opening a gitter channel for this project? I think I remember a talk where @non mentioned that it contributed Cats growing community but maybe I made that part up.

**Comment by DanielAsher** [comment]
I promoted the creation of a slack channel... but it's pretty lonely their at the mo. Will look into gitter.

**Comment by adamkuipers** [comment]
What's nice about gitter is that it's discoverable. And you don't need a slack account.

**Comment by DanielAsher** [comment]
right. slack is imperfect for unpaid use.

**Comment by pthariensflame** [comment]
Having read through this three, I've just created https://gitter.im/typelift and invite @CodaFi.  Anyone else want in?

**Comment by DanielAsher** [comment]
I'd love to give gitter a go.

**Comment by adamkuipers** [comment]
Is it not going to be a public channel?

**Comment by pthariensflame** [comment]
I guess we can make it public, but I don't know how to do that!

**Comment by adamkuipers** [comment]
Isn't it just "Create Room" -> Repository -> Swiftz?

**Comment by pthariensflame** [comment]
Maybe?  I'm on mobile right now, so it'll have to wait for a few hours.

**Comment by pthariensflame** [comment]
Okay, https://gitter.im/typelift/general has just been created, and it's public!

**Comment by DanielAsher** [comment]
Hurrah!

**Comment by joamaki** [comment]
Btw, regarding the need for the boilerplate curried constructor, in Swift 2 this now works:

```swift
struct Foo { let a: Int, let b: String }
curry(Foo.init) <^> 1 <*> "hello"
```

Of course you'll end up hitting the "expression too complex" pretty quickly...

**Comment by CodaFi** [comment]
Whatever happened to this proposal?  Should I draw up the pull request for this myself?
