### ISSUE TITLE
Swiftz to use Runes and Curry

### ISSUE THREAD

**Issue by mpurland** [typelift/Swiftz#262]
What do you think about having Swiftz use Runes and Curry to enable code reuse?

**Comment by CodaFi** [comment]
We have our own solution, Operadics, because Runes is woefully incomplete.  Our operators are 100% compatible with Runes when imported into the same translation unit if it helps.

**Comment by mpurland** [comment]
That makes sense. Thanks.

**Comment by CodaFi** [comment]
Great. I'll close this, then.
