### ISSUE TITLE
Swiftz and Argo

### ISSUE THREAD

**Issue by mpurland** [typelift/Swiftz#263]
I am using Swiftz in multiple projects, but the JSON decoder is not complete. Have you thought about having Swiftz use or extend Argo?

**Comment by mpurland** [comment]
To fix the issues with the JSON decoder related to NSNumber. Would you be open to pull requests to fix it?

**Comment by CodaFi** [comment]
"Not complete" in the sense that we don't cover Foundation classes is a feature, not a bug.  Foundation, and the implicit overloads it introduces, need to stay as far away from us as possible.  Use our existing instances as a guide for writing out the missing ones.

**Comment by CodaFi** [comment]
We would be open to having a standard repo/gist extending Swiftz with Foundation support. Hell, a new library splitting out the JSON stuff may even be called for (or we could remove it altogether, but then we'd get issues screaming at us about it.

**Comment by mpurland** [comment]
@CodaFi I was thinking that as well. Mainly, there's an issue around the numbers implementation in JSON. It doesn't fully support integers and unsigned long integers. I was thinking to add on to JSONValue with support for Int, Int64, and Float. I'm fully prepared to fix it.

```swift
extension Int : JSON {
	public static func fromJSON(x : JSONValue) -> Int? {
		switch x {
		case let .JSONNumber(n):
			return Int(n)
		default:
			return Optional.None
		}
	}

	public static func toJSON(xs : Int) -> JSONValue {
		return JSONValue.JSONNumber(Double(xs))
	}
}
```

Notice it is a JSON extension to Int, but fromJSON lets the JSONNumber (which is currently only a Double) to an Int. Also, toJSON here converts the Int to a JSONNumber with a Double value.

Example JSON:
```json
{
    "id" : 103622342330925644
}
```

But when loaded in with Swiftz, it becomes 1.036223423309256e+17.
A failed unit test fails with: failed - expected to equal <103622342330925644>, got <1.036223423309256e+17>

Does a pull request with those outlined additions/fixes sound good?

**Comment by mpurland** [comment]
Submitted PR #264

**Comment by mpurland** [comment]
Closing this as #264 was merged.
