### ISSUE TITLE
Literal collection types

### ISSUE THREAD

**Issue by mpurland** [typelift/Swiftz#272]
I was thinking about updating the extensions around concrete types where literal syntax is applicable. An example would be updating ArrayExt to use `[Type]` instead of `Array<Type>` syntax. 

Any thoughts?

**Comment by CodaFi** [comment]
Sure.  But I think we should draw the line at collapsing `Optional` to `?`.  If anything, Optional needs to be as expanded as possible in type signatures so it's obvious that we treat it as a datatype and not as the syntactic sugarhigh it is.

**Comment by mpurland** [comment]
That makes sense. I'll draw up a PR.

**Comment by mpurland** [comment]
PR #273

**Comment by CodaFi** [comment]
Done!
