### ISSUE TITLE
Algebraic data types

### ISSUE THREAD

**Issue by mpurland** [typelift/Swiftz#276]
I was working on algebraic data types and looked at NumericType. Any thoughts about the following?

Commit: df501564ebb69b5095f1f09ed1557f11dc924ce6

**Comment by CodaFi** [comment]
I don't know what we gain by each unless you intend to rename Addable and Multipliable to some Semigroup puns, Subtractable as the mate of Semigroup and Invertable and move Signum somewhere else entirely.  Basically, I think Haskell's authors, when they were writing Num, just shot for the minimum viable structure they could start defining easy arithmetic operations on.

For what it's worth, this would go great in the [Algebra](github.com/TypeLift/Algebra) package, though.

**Comment by mpurland** [comment]
Should I move this over to Algebra?

**Comment by CodaFi** [comment]
Yeah.  First I have to see if that thing doesn't crash Swiftc and merge that leftover PR.  Could you open the build script pull request over there too while you're at it>

**Comment by mpurland** [comment]
How I long for the days that Swiftc doesn't crash...

Will do. I'll update the remaining projects with the build scripts this evening.
