### ISSUE TITLE
Operators documentation

### ISSUE THREAD

**Issue by sendyhalim** [typelift/Swiftz#278]
Hi there, just curious why the operators documentation (table) was removed?

Found it removed in this commit https://github.com/typelift/Swiftz/commit/fb6bcb5a6d750ad887190fc5be89a9c1626e5826

It would be easier for a newbie like me to see the operators that are provided by Swiftz

**Comment by CodaFi** [comment]
That was moved into the [Operadics](https://github.com/typelift/Operadics) README because those operators now apply to every repository in TypeLift not just Swiftz.

**Comment by sendyhalim** [comment]
Oh nice, thanks! :beers:
