### ISSUE TITLE
Any plans to add Reader monad?

### ISSUE THREAD

**Issue by mathonsunday** [typelift/Swiftz#281]
I see there is already a Writer monad. I'd be interested in a Reader monad for Dependency Injection. Any plans to add it?

**Comment by CodaFi** [comment]
Absolutely.  Would you like to contribute an implementation, or shall I?

**Comment by mpurland** [comment]
A reader monad would be nice. :+1:

**Comment by mathonsunday** [comment]
I'll contribute something and then you all can let me know what you think.

**Comment by mathonsunday** [comment]
I spent Sunday working on an implementation in line with other ones in the project. Unfortunately I wasn't able to get it into a functional state. Need to get a better understanding of it myself. I'm with my family for the next week so someone else is free to contribute the implementation.

**Comment by mpurland** [comment]
I can take a look and see what I can come up with unless you want to @CodaFi?

**Comment by CodaFi** [comment]
@mpurland Wanna race?  😬

**Comment by mpurland** [comment]
Here's my first attempt. Let me know what you think of the PR. 

#284

**Comment by CodaFi** [comment]
With the merge of #284, this issue is now closed.

Thanks everybody! :sparkles:

**Comment by mpurland** [comment]
:+1:
