### ISSUE TITLE
Swift.match() instead of a computed properties?

### ISSUE THREAD

**Issue by gcornut** [typelift/Swiftz#291]
Hi, is there any reason why String.match is a method rather than a computed property (like in Array and List)?

**Comment by CodaFi** [comment]
At this point, not really.  Wanna write us a pull request ;)

**Comment by gcornut** [comment]
Ok sure, should I do it on swift-develop or master?

**Comment by CodaFi** [comment]
Submit it to master please.

**Comment by mpurland** [comment]
Resolved. See #293
