### ISSUE TITLE
Consider `Array.groupBy` to use adjacent element predicate rather than span.

### ISSUE THREAD

**Issue by DanielAsher** [typelift/Swiftz#306]
Version
========

v0.5.0 - 78665a0921857ce6b1408bd91a5069931cab0191

Environment
===========

Mac OS X

Description
============

`Array.groupBy` behaves in an unexpected manner. Though the comment implies the predicate is applied to adjacent elements, span actually applies the predicate to non-adjacent elements

Steps To Reproduce
===================
```
import Swiftz

let sawtooth = [1,2,3,2,3,4]
let groups = sawtooth.groupBy { $0 < $1 }
```
Expected Result
================

`groups` to equal `[[1, 2, 3], [2, 3, 4]]`
Actual Result
==============

`groups` equals `[[1, 2, 3, 2, 3, 4]]`

Additional information
======================

This may be the intended behaviour, but I believe standard implementations of groupBy use their predicate on adjacent elements.

**Comment by DanielAsher** [comment]
Here's an implementation I'm using - no List mojo I'm afraid :-/
```
extension Array {
    // group into subarrays by applying predicate to adjacent elements in the source array.
    // let groups = [1,2,3,2,3,4].groupAdjacent { $0 > $1 } 
    // groups == [[1,2,3], [2,3,4]]
    func groupAdjacent(predicate: (Element, Element) -> Bool) -> [[Element]] {
        guard let head = self.first else { return [] }
        return self.dropFirst().reduce( [[head]] ) { xss, x in
            guard let last = xss.last!.last else { return xss }
            var xssc = xss // copy required to mutate
            predicate(last, x) ? xssc[xss.count-1].append(x) : xssc.append([x])
            return xssc
        }
    }
}
```

**Comment by CodaFi** [comment]
We based our implementation on Haskell, and your example behaves as intended if that is the semantics we're after.

**Comment by DanielAsher** [comment]
Oops - the predicate in the example should read `{ $0 < $1 }` of course. 

OK - understood. I'll close this one.
