### ISSUE TITLE
114 warnings Xcode 9.1

### ISSUE THREAD

**Issue by BrianDoig** [typelift/Swiftz#329]
Version
========

c0c22789ede4aa036c52aa5c8ec5fc5378877fd1

Environment
===========

Xcode Version 9.1 (9B55)
iOS 11.0

Description
============

The warnings all seem to be similar to the following
redundant conformance constraint 'W': 'Monoid'
redundant conformance constraint 'T': 'IntegralType'
'characters' is deprecated: Please use String or Substring directly

Steps To Reproduce
===================

Build with Xcode 9.1

Expected Result
================

Zero warnings

Actual Result
==============

113 Warnings

Additional information
======================

.build/checkouts/Swiftz-8362753330373533918/Sources/Writer.swift:84:22: warning: redundant conformance constraint 'W': 'Monoid'
public func <^> <W : Monoid, A, B>(_ f : (A) -> B, w : Writer<W, A>) -> Writer<W, B> {
                     ^
.build/checkouts/Swiftz-8362753330373533918/Sources/Writer.swift:84:56: note: conformance constraint 'W': 'Monoid' inferred from type here
public func <^> <W : Monoid, A, B>(_ f : (A) -> B, w : Writer<W, A>) -> Writer<W, B> {
                                                       ^
.build/checkouts/Swiftz-8362753330373533918/Sources/Writer.swift:104:22: warning: redundant conformance constraint 'W': 'Monoid'
public func <*> <W : Monoid, A, B>(wfs : Writer<W, (A) -> B>, xs : Writer<W, A>) -> Writer<W, B>  {
                     ^
.build/checkouts/Swiftz-8362753330373533918/Sources/Writer.swift:104:42: note: conformance constraint 'W': 'Monoid' inferred from type here
public func <*> <W : Monoid, A, B>(wfs : Writer<W, (A) -> B>, xs : Writer<W, A>) -> Writer<W, B>  {
                                         ^
.build/checkouts/Swiftz-8362753330373533918/Sources/Ratio.swift:38:21: warning: redundant conformance constraint 'T': 'IntegralType'
public func == <T : Equatable & IntegralType>(l : Ratio<T>, r : Ratio<T>) -> Bool {
                    ^
.build/checkouts/Swiftz-8362753330373533918/Sources/Ratio.swift:38:51: note: conformance constraint 'T': 'IntegralType' inferred from type here
public func == <T : Equatable & IntegralType>(l : Ratio<T>, r : Ratio<T>) -> Bool {
                                                  ^
.build/checkouts/Swiftz-8362753330373533918/Sources/Writer.swift:190:30: warning: redundant conformance constraint 'W': 'Monoid'
public func == <W : Monoid & Equatable, A : Equatable>(l : Writer<W, A>, r : Writer<W, A>) -> Bool {
                             ^
.build/checkouts/Swiftz-8362753330373533918/Sources/Writer.swift:190:60: note: conformance constraint 'W': 'Monoid' inferred from type here
public func == <W : Monoid & Equatable, A : Equatable>(l : Writer<W, A>, r : Writer<W, A>) -> Bool {
                                                           ^
.build/checkouts/Swiftz-8362753330373533918/Sources/StringExt.swift:55:11: warning: 'characters' is deprecated: Please use String or Substring directly
                if self.characters.count == 0 {
                        ^
.build/checkouts/Swiftz-8362753330373533918/Sources/StringExt.swift:57:18: warning: 'characters' is deprecated: Please use String or Substring directly
                } else if self.characters.count == 1 {
                               ^
.build/checkouts/Swiftz-8362753330373533918/Sources/StringExt.swift:29:10: warning: 'characters' is deprecated: Please use String or Substring directly
                return characters.split(maxSplits: Int.max, omittingEmptySubsequences: false) { $0 == token }.map { String($0) }
                       ^
.build/checkouts/Swiftz-8362753330373533918/Sources/StringExt.swift:218:21: warning: 'characters' is deprecated: Please use String or Substring directly
                return Array(self.characters).map(f).reduce("", +)
                                  ^
.build/checkouts/Swiftz-8362753330373533918/Sources/StringExt.swift:227:40: warning: 'characters' is deprecated: Please use String or Substring directly
        return sequence(ms.map { m in Array(m.characters) }).map(String.init(describing:))

**Comment by CodaFi** [comment]
Resolved by [version 0.7.0](https://github.com/typelift/Swiftz/releases/tag/0.7.0).
