### ISSUE TITLE
Swift 4.0.2 support

### ISSUE THREAD

**Issue by BrianDoig** [typelift/Swiftz#330]
Version
========

c0c22789ede4aa036c52aa5c8ec5fc5378877fd1

Environment
===========

Xcode Version 9.1 (9B55)
iOS 11

Description
============

The library is currently compiling against Swift 3.2 instead of Swift 4.0.

Steps To Reproduce
===================

Check out project, and in Xcode go to Edit -> Convert -> To Current Swift Syntax.  It shows that the project needs to be updated.

Expected Result
================

The library should be supporting the latest version of Swift syntax.

Actual Result
==============

Library does not support the latest Swift version.

**Comment by CodaFi** [comment]
Resolved by [version 0.7.0](https://github.com/typelift/Swiftz/releases/tag/0.7.0).
