### ISSUE TITLE
Swiftz source missing from Pods

### ISSUE THREAD

**Issue by ryanbooker** [typelift/Swiftz#335]
When integrating the latest pod via git (rather than the pod repo), there is no source in the Swiftz pod.

**Comment by CodaFi** [comment]
I'm unsure of what I'm suppose to do to fix this.

**Comment by ryanbooker** [comment]
Me either. Just noting that it no longer works (I was using Carthage, but need to move to Cocoapods).

**Comment by CodaFi** [comment]
You ought to bring this up with the CocoaPods folks then.  I've clueless when it comes to our pod specs (if they pass validation, it ships).

**Comment by ikesyo** [comment]
You should specify `:submodules => true` option.

**Comment by ikesyo** [comment]
And also this line does not matches current layout:

https://github.com/typelift/Swiftz/blob/0f9c0d9fbed34a6e67ecc2233b44f3076e3f2e8f/Swiftz.podspec#L15

**Comment by ikesyo** [comment]
Submitted #336

**Comment by ryanbooker** [comment]
Ah! Great. Thanks you for the tip and the fix. Cheers.
