### ISSUE TITLE
Lenses for JSON

### ISSUE THREAD

**Issue by mxswd** [typelift/Swiftz#58]
The JSON objects should be traversable by lenses (, prisms and traversals).

We should also consider zippers with error reporting, like in Argonaut.

**Comment by CodaFi** [comment]
The Traversals side of this is causing a lot of headaches.  I need quantification over Applicative things of kind `* -> *` otherwise I'm stuck `unsafeBitCast`'ing a solution I neither need nor want.

**Comment by mpurland** [comment]
It would be nice to update the JSON error handling to return an Either for JSON results of the given type or an error.

**Comment by CodaFi** [comment]
JSON has been moved out of the framework.
